### ISSUE TITLE
Symbol not found when launching europa.

### ISSUE THREAD

**Issue by rvlander** [nasa/europa#177]
#### Configuration:
 * OpenJDK 1.8
 * ftjam 2.5.3
 * GCC  7.2.0
 * libantlr3c 3.5.2

I am trying to follow the quick start guide (using official binaries); When launching `ant` I have the following error:
```
Buildfile: /home/gandre/WIP/Aeroport/Planning/Light/build.xml

init:

compile:

run:
     [echo] Running Light project
     [java] INFO: Custom library Light_g wasn't found and won't be loaded.
     [java] /usr/lib/jvm/java-8-openjdk/jre/bin/java: symbol lookup error: /home/gandre/WIP/Aeroport/Planning/europa//lib/libNDDL_g.so: undefined symbol: antlr3AsciiFileStreamNew

BUILD FAILED
/home/gandre/WIP/Aeroport/Planning/Light/build.xml:69: Java returned: 127
```
I expect it to be because of libantrl3c version conflicts.

**Comment by miatauro-NASA** [comment]
I expect you're right.  The official binaries need libantlr3c 3.1.3, and there was a change in the names and signatures of the ANTLR3 file stream opening functions between that and later available versions.  I strongly recommend building from source (which I notice you tried in #176, and I'll be looking at in a second).

**Comment by miatauro-NASA** [comment]
If you want to install the required version of libantlr3c, just grab it from http://www.antlr3.org/download/C/libantlr3c-3.1.3.tar.gz
Closing this for now.  Please feel free to re-open if you decide to pursue this route and that doesn't work.

**Comment by smithdtyler** [comment]
> If you want to install the required version of libantlr3c, just grab it from http://www.antlr3.org/download/C/libantlr3c-3.1.3.tar.gz
> Closing this for now. Please feel free to re-open if you decide to pursue this route and that doesn't work.

Note that this version of ANTLR seems to default to compiling a 32bit library, use 

```
./configure --enable-64bit 
sudo make install-libLTLIBRARIES
```

To deploy a 64bit shared version of ANTLR library
