### ISSUE TITLE
Specify misbehaving in the temporal network

### ISSUE THREAD

**Issue by miatauro-NASA** [nasa/europa#77]
_From [None](https://code.google.comNone) on May 07, 2010 10:53:26_

_Original issue: http://code.google.com/p/europa-pso/issues/detail?id=77_

**Comment by miatauro-NASA** [comment]
I'll be committing a slightly expanded version of the test for this later today (TemporalPropagatorTest::testSpecification), but I can't seem to reproduce the issue or find a commit that mentions fixing it.  Maybe @phmorris  has a test case.

**Comment by phmorris** [comment]
My memory on this is hazy.  I think Javier fixed it.  (Probably the 
un-commented commit.)  I don't have a test case lying around.

Paul

**Comment by miatauro-NASA** [comment]
In that case, I'm closing this.
